Add GitHub workflow for updating cacert.pem certificate bundle
LibreELEC/actions pull request #24
Opened 2022-10-11 10:16 UTC by heitbaum

The workflow is scheduled to run every day at 11.30am UTC and it can optionally be triggered manually.

Originally from: https://github.com/Slicer/Slicer/blob/main/.github/workflows/update-slicer-certificate-bundle.yml

Adapted for LibreELEC/actions

Co-authored-by: Rudi Heitbaum <rudi@heitbaum.com>

Secret: `LIBREELECBOT_GITHUB_TOKEN`: is required with `public_repo` permissions in the actions repo to checkout and create the PR in LibreELEC/LibreELEC.tv

Reading materials:
- https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork

2022-10-11 13:56 UTC, CvH requested changes

2022-10-11 13:56 UTC, CvH commented on .github/workflows/update-cacert-pem-certificate-bundle.yml
> +          #push-to-fork
```suggestion
```

2022-10-11 13:56 UTC, CvH commented on .github/workflows/update-cacert-pem-certificate-bundle.yml
> +            [3]: https://github.com/${{ github.repository }}/blob/${{ steps.head_branch.outputs.sha }}/.github/workflows/update-cacert-pem-certificate-bundle.yml
```suggestion
            cacert.pem: update to ${{ steps.latest_certdata.outputs.authordate }}

            This commit updates cacert.pem certificate bundle with [mk-ca-bundle.pl] script using the
            content of [certdata][1] associated with ${{ env.CERTDATA_OWNER }}/${{ env.CERTDATA_REPO }}@${{ steps.latest_certdata.outputs.sha }},

            [1]: ${{ steps.latest_certdata.outputs.download_url }}
}}/.github/workflows/update-cacert-pem-certificate-bundle.yml
```

2022-10-11 13:56 UTC, CvH commented on .github/workflows/update-cacert-pem-certificate-bundle.yml
> +            [3]: https://github.com/${{ github.repository }}/blob/${{ steps.head_branch.outputs.sha }}/.github/workflows/update-cacert-pem-certificate-bundle.yml
I think less chatty is good enough?

2022-10-11 13:56 UTC, CvH commented on .github/workflows/update-cacert-pem-certificate-bundle.yml
> +# Date:   Tue Sep 14 18:32:49 2021 -0400 - Wed Mar 16 02:45:45 2022 -0400
```suggestion
# Author: Jean-Christophe Fillion-Robin
```

2022-10-11 13:56 UTC, CvH commented on .github/workflows/update-cacert-pem-certificate-bundle.yml
> +# Date:   Tue Sep 14 18:32:49 2021 -0400 - Wed Mar 16 02:45:45 2022 -0400
I would not add his email here.

2022-10-11 22:18 UTC, heitbaum commented on .github/workflows/update-cacert-pem-certificate-bundle.yml
> +# Date:   Tue Sep 14 18:32:49 2021 -0400 - Wed Mar 16 02:45:45 2022 -0400
all updated :-)

2022-10-13 14:54 UTC, CvH approved these changes

2022-10-13 14:54 UTC, merged